sudo: true
language: android
android:
        components:
                - platform-tools
                - build-tools-26.0.2
                - android-23
                - extra-android-m2repository
                - extra-android-support
                - extra-google-google_play_services
                - extra-google-m2repository
script:
        # Override Travis default script to not run connectedCheck until this bug is fixed:
        # https://code.google.com/p/android/issues/detail?id=59592
        - ./gradlew clean build findbugs -PdisablePreDex
        - ./print_findbugs.sh
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master
before_cache:
        # Delete the gradle lock file which forces creation of a new build cache
        - rm ~/.gradle/caches/modules-2/modules-2.lock
cache:
        directories:
        - ~/.gradle
