sudo: true
language: android
android:
        components:
                - platform-tools
                - build-tools-26.0.2
                - android-23
                - extra-android-m2repository
                - extra-android-support
                - extra-google-google_play_services
                - extra-google-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
